### ISSUE TITLE
May I use your DirectX code for my project?

### ISSUE THREAD

**Issue by vmx17** [EmmettTsai/SpinningCube#1]
Hi! I'm sorry openning issue in this repository. This is not an issue, but just asking.
May I use your DirectX code on this project for my project? I know it is MIT lisence but I think I should confirm your team.
I'm now prototyping a desktop draw application using DirectX (I'm new to DirectX). In the project, I'm planning to implement interop XAML, C#, C\++, DirectX and Windows App SDK. As a base frame, I'll use C# for productivity that construct MVVM architecture, and for Drawing, I'll use C\++/WinRT driven DirectX for performance. So I have to prove such implementation is possible or not. I think your code seems very handy to port to such archtecture.

And, I think your code here seems a part of some other large original code. If it is open source, please point me the URL.

**Comment by EmmettTsai** [comment]
Of course.
The source of this project was created from the Visual Studio project template
"DirectX 11 and XAML App (Universal Windows - C++/CX)."
I only used it to practice porting to WinUI3.

At that time, I encountered an issue related to input:
https://github.com/microsoft/WindowsAppSDK/issues/2720

I actually don't know much about DirectX.
I only did a little research on it because it was somewhat related to a project I worked on before.
I vaguely remember referencing the following official samples, which I hope will be helpful to you.

https://github.com/microsoft/DirectX-Graphics-Samples
https://github.com/microsoft/DirectXMath
https://github.com/microsoft/DirectXMesh
https://github.com/microsoft/DirectXTex
https://github.com/microsoft/DirectXTK

https://github.com/microsoft/MixedRealityToolkit
https://github.com/microsoft/MixedRealityToolkit/tree/main/SpatialInput/Samples/RenderController

https://github.com/microsoft/Windows-universal-samples/tree/main/Samples
D2DAdvancedColorImages
D2DCustomEffects
D2DGradientMesh
D2DPhotoAdjustment
D2DSvgImage

**Comment by vmx17** [comment]
Hi! Thank you for many information. Because I've never used C++/CX (nor UWP), I did not know the template. I've been using C# only before C++/WinRT.  
[Here](https://github.com/vmx17/ProtoWRC) is the project I've just make public. Now I know there are more things to learn.
